### ISSUE TITLE
Datasets - Prioritize the indices

### ISSUE THREAD

**Issue by MarcAndreDubuc** [CanadianClimateDataPortal/Canadian-Climate-Data-Portal#11]

**Comment by MarcAndreDubuc** [comment]
Derek comment: «After a chat with Travis, I will take a first pass at prioritizing the indices and post my suggestions on Confluence.»

**Comment by tomLandry** [comment]
In order to draw the line to the number of indices we want to use in the list, we need to consider closely data volume constraints (downloading, ingesting) found here https://github.com/CanadianClimateDataPortal/Canadian-Climate-Data-Portal/issues/29
