### ISSUE TITLE
Compute all prioritized indices on BCCAQv2

### ISSUE THREAD

**Issue by MarcAndreDubuc** [CanadianClimateDataPortal/Canadian-Climate-Data-Portal#14]
Name (ICCLIM) | Description
-- | --
warm day frequency | Number of days per year when Tmax >30°C; 35degC
warm night frequency | Number of days per year when Tmin >22°C; number of days per year when Tmin >25°C
Heat waves frequency | Number of events per year of 3 consecutive days when Tmin > 22°C and Tmax > 30°C
Heating degree days | sum of threshold 'T' minus daily Tavg for days when TAvg<=T
Cooling degree days | sum of Tavg minus threshold 'T' for days when TAvg>=T
TG (ICCLIM) | Mean of daily mean temperature
TXX (ICCLIM) | Maximum of daily maximum temperature
TN (ICCLIM) | Mean of daily minimum temperature
TG10p (ICCLIM) | Days with TG < 10th percentile of daily mean temperature (cold days)
TG90p (ICCLIM) | Days with TG > 90th percentile of daily mean temperature (warm days)
CDD (ICCLIM) | Maximum number of consecutive dry days (RR < 1 mm)
CWD (ICCLIM) | Maximum number of consecutive wet days (RR>= 1 mm) (days)
FD (ICCLIM) | Frost days (TN < 0◦C)
GDN (ICCLIM) | Growing degree days (sum of TG > N ◦C) ; Default 4 deg C
TX (ICCLIM) | Mean of daily maximum temperature
hot minimum and maximum temp. frequency | Number of days per year when Tmin > 22°C and Tmax>30°C
Freeze thaw cycle frequency | Number of days/year when Tmin<0°C and Tmax>0°C
RR1mm (ICCLIM) | Wet days (RR >= 1 mm)
RNmm (ICCLIM) | Very heavy precipitation days (precipitation >= N mm); Default 20mm
RX1day (ICCLIM) | Highest 1-day precipitation amount
PRCPTOT (ICCLIM) | Total precipitation (liquid and solid combined)
SDII (ICCLIM) | Simple daily intensity index (mm/wet day)
R95p (ICCLIM) | Days with RR > 95th percentile of daily amounts (very wet days)
R95pTOT (ICCLIM) | Precipitation fraction due to very wet days (> 95th percentile) (%)
RXNday (ICCLIM) | Highest N-day precipitation amount
GSL (ICCLIM) |

**Comment by tomLandry** [comment]
@tlogan2000 could you give a little update on the state of the computations? Even if it's not *ALL* indices, I'd like to know if we have the prioritized indices pretty much covered https://ccdpwiki.atlassian.net/wiki/spaces/CCDP/pages/54919256/Indices+prioritization. Next step if to make sure transfer of data is made to @habitatseven

**Comment by tlogan2000** [comment]
We have the code to calculate them I think.  I am not sure time remaining will allow us to get through the entire priority list.  Discussing with hab7 last week we had planned to start at the top and work our way down the list ... Therefore currently 'heat waves' calculations are running (after a few debugs/issues with xarray were solved last week).  @tomLandry I will be at CRIM thursday to look at finch wps with d. caron ...are you available to discuss in person for 15-20 min?

**Comment by tomLandry** [comment]
Yes, thanks Travis. I can do better than that! We do have a work session with Jamie at CRIM this Thursday, from 10:00 to 13:00. Perfect time to recap.

**Comment by tlogan2000** [comment]
Perfect!

**Comment by tomLandry** [comment]
@dbyrns same idea here. Travis sent us a table with all ANUSPLIN and BCCAQv2 computed data, hosted on THREDDS. This issue here was more on the BCCAQv2 side. We might now have them "all" or by prioritization, but we're pretty much there. I would close this an open more specific issues down the road for computation of indices.

**Comment by tomLandry** [comment]
Majority of indices now on THREDDS server, moving into QA.
