### ISSUE TITLE
User engagement - General portal

### ISSUE THREAD

**Issue by MarcAndreDubuc** [CanadianClimateDataPortal/Canadian-Climate-Data-Portal#19]

**Comment by tomLandry** [comment]
Requests sent to: 

Gord Beal: VP at CPA Canada 
Fiona Warren: NRCAN
Anna Pirani: TSU Lead IPCC Working Group I
Blane Harvey: McGill University
Brian Sieban: ECCC
John Wade: Underwriters Laboratories

**Comment by MarcAndreDubuc** [comment]
See documentation here: https://ccdpwiki.atlassian.net/wiki/spaces/CCDP/pages/64487532/General+portal+-+User+engagement+report

**Comment by tomLandry** [comment]
Isabelle's comment constitutes for me a validation of the work.
