### ISSUE TITLE
Present a gridded map of Canada

### ISSUE THREAD

**Issue by MarcAndreDubuc** [CanadianClimateDataPortal/Canadian-Climate-Data-Portal#2]
- [x] 10x10 km gridded cell
- [ ] Show provinces and territories boundaries https://github.com/CanadianClimateDataPortal/Canadian-Climate-Data-Portal-2/issues/22
- [ ] Show major cities and point of interest
- [ ] Number of zooming level
- [ ] Quick interaction with the map (zooming, scrolling, etc.)

**Comment by tomLandry** [comment]
Demonstrated in demo app from @habitatseven. Further issues on this will be created individually on the pre-production version, or after launch.
