### ISSUE TITLE
Survey for user engagement - Health module

### ISSUE THREAD

**Issue by MarcAndreDubuc** [CanadianClimateDataPortal/Canadian-Climate-Data-Portal#20]

**Comment by tomLandry** [comment]
As discussed with @isacharron, a summary is now needed. Abder will validate.

**Comment by tomLandry** [comment]
Linked to https://github.com/CanadianClimateDataPortal/Canadian-Climate-Data-Portal/issues/51 which is the next logical step

**Comment by tomLandry** [comment]
Survey results and summary can be found here: https://ccdpwiki.atlassian.net/wiki/spaces/CCDP/pages/64520195/Survey+results
Thanks @isacharron, great work !
