### ISSUE TITLE
Packaging and deploying Finch

### ISSUE THREAD

**Issue by MarcAndreDubuc** [CanadianClimateDataPortal/Canadian-Climate-Data-Portal#25]

**Comment by tomLandry** [comment]
Deployed for validation by @tlogan2000 as documented here https://ccdpwiki.atlassian.net/wiki/spaces/CCDP/pages/11960337/Deployments and by email. Uses XClim packaged in a self-contained server (a bird) called Finch. Deployed server is then proxyied by Twitcher and uses a RESTful API.

**Comment by tomLandry** [comment]
As demonstrated on Jan 31 by David Caron to Travis Logan.
