### ISSUE TITLE
Demonstrate web mapping capabilities

### ISSUE THREAD

**Issue by MarcAndreDubuc** [CanadianClimateDataPortal/Canadian-Climate-Data-Portal#34]

**Comment by dbyrns** [comment]
@habitatseven I have seen a demo page for time series, but is there a demo available for the web mapping capabilities using your tiles?

**Comment by tomLandry** [comment]
I've asked Jamie to provide a web mapping sample for tiled gridded data. The demo should be added to the other one we've been sent.

**Comment by tomLandry** [comment]
Closing the issue on web mapping for time series, as well as gridded tests. Demonstration of tiling still pending.

**Comment by dbyrns** [comment]
If it's still pending why closing it right now? Unless you have another issue tracking it this is the best way to forget about it.

**Comment by tomLandry** [comment]
Other issue is indeed already logged, with Top priority (blocker). See linked issues. That follows a discussion between Marc-André, Jamie and me on the phone.
