### ISSUE TITLE
Ingest monthly data in Postgres database

### ISSUE THREAD

**Issue by MarcAndreDubuc** [CanadianClimateDataPortal/Canadian-Climate-Data-Portal#37]

**Comment by tomLandry** [comment]
Initial tests results for (1 var, 1 RCP, 1 Model, 150 year, Monthly) are about 150 minutes per processor. Current work is focused on enabling multiprocessor capability, bringing potential ingest time to about 20 minutes.

**Comment by tomLandry** [comment]
Demonstrated successfully at CRIM on Jan 31 to Tom Landry and David Byrns. As expected!
