### ISSUE TITLE
Compute indices on ANUSPLIN

### ISSUE THREAD

**Issue by tomLandry** [CanadianClimateDataPortal/Canadian-Climate-Data-Portal#42]

**Comment by tomLandry** [comment]
As discussed this morning, CRIM's Finch instance is processing ANUSPLIN data, and not BCCAQv2. One idea would be to continue concentrating efforts on this dataset for CRIM's deployment.

**Comment by tlogan2000** [comment]
Just a note I am actually not using finch but directly xclim installed in a conda environment

**Comment by tomLandry** [comment]
Ok, that's absolutely fine short-medium term. In an ideal world, we would call Finch in the analytics page of the portal for a very limited subset of the indices and thresholds.  For now, this issue is about data preparation in order to feed the PostGres database.

**Comment by dbyrns** [comment]
I see that this task should now be validated... @tlogan2000 are you done generating the indices on ANUSPLIN?

**Comment by tlogan2000** [comment]
This is ongoing but many are done and could be validated 
See tracking table we set up on confluence
https://ccdpwiki.atlassian.net/wiki/spaces/CCDP/pages/57638919/Interim+Prioritization

**Comment by tomLandry** [comment]
From what I see, that particular task is ready to be validated. It's more about knowing we can compute indices on ANUSPLIN in a structured way. For me its convincing. For data QA, see https://github.com/CanadianClimateDataPortal/Canadian-Climate-Data-Portal/issues/43

**Comment by dbyrns** [comment]
Ok I agree with you Tom. And this is good to have a direct link for the progress too.
Maybe we should then add a task for the generation of the whole dataset identify for the launch?

**Comment by dbyrns** [comment]
And for the validation, I guess that we will need a confirmation from @habitatseven that the data has been ingested properly.

**Comment by tomLandry** [comment]
Mmm... yeah, that would be the best but the issue is about computation only. Indices can be computed, data proves it. For ingestion, I would open another task. That being said, yes, further down the line the best validation is consumption.

**Comment by dbyrns** [comment]
Ok so given that data integrity will be checked by this issue : https://github.com/CanadianClimateDataPortal/Canadian-Climate-Data-Portal/issues/43
And the fact that data are being produced properly I guess that the validation is completed and we can close this issue.

**Comment by tomLandry** [comment]
Yes. For ANUSPLIN, it's less a Big Data problem than BCCAQv2. To demonstrate some integration to the portal, I would go more for integration in the designs and mouting of a few samples as tiles. But for BCCAQv2, that's where it hurts for data volume: thus https://github.com/CanadianClimateDataPortal/Canadian-Climate-Data-Portal/issues/48 as blocker right now. The famous equation of how heavy will be an indices once ingested in the portal (or unchunked, uncompressed for speed).
