### ISSUE TITLE
QA and checks of data uploaded to THREDDS

### ISSUE THREAD

**Issue by tomLandry** [CanadianClimateDataPortal/Canadian-Climate-Data-Portal#43]
Follow up on https://github.com/Ouranosinc/pavics-sdi/issues/37

**Comment by tomLandry** [comment]
@dbyrns for your information, here we have Prairie Climate Center (PCC) experts' that will sample several of these data outputs and analyze them for correctness, completeness, quality.

**Comment by dvdkamp** [comment]
Please let me know if more support is needed on this issue. I can certainly do some QA on the data as well...

**Comment by tlogan2000** [comment]
I added @dvdkamp and @ryanclimateatlas on this.  I would concentrate on the ensemble statistics files
for now ... making some maps and figures of these and validating that outputs seem reasonable would be a great help
https://ccdpwiki.atlassian.net/wiki/spaces/CCDP/pages/57638919/Interim+Prioritization

**Comment by ryanclimateatlas** [comment]
I will be gearing up to perform some checks of the ensemble stat files next week.  In the meantime, there were two unidentified issues already mentioned: 1) the lat/lon values in these stat files are shifted half a grid point; and 2) the ANUSPLIN unadjusted precipitation values were consistently too low across the map, while the adjusted were often too high.

**Comment by tomLandry** [comment]
I like Travis idea of producing maps. That can be automated quite easily, can give us useful thumbnails, and can be inspected for anomalies even by "climate untrained" specialists.

**Comment by tlogan2000** [comment]
@ryanclimateatlas 
For coordinate issues do you have specific files where you are seeing this on my end with the files I chose everything seems ok and passes all my assertion tests.

BCCAQv2 raw and indices have identical values
NRCAN an BCCAQV2 are identical to 5 dec places 

Note anusplin latitudes are descending in order hence the flip of the lat array before the tests

code
```python
import xarray as xr
import numpy as np

url_ind = 'http://boreas.ouranos.ca:8083/thredds/dodsC/birdhouse/cccs_portal/indices/Final/BCCAQv2/txgt_30/YS/rcp85/ensemble_percentiles/BCCAQv2+ANUSPLIN300_ensemble-percentiles_historical+rcp85_1950-2100_txgt_30_YS.nc'
url_raw = 'http://boreas.ouranos.ca:8083/thredds/dodsC/birdhouse/pcic/BCCAQv2/tasmax_day_BCCAQv2+ANUSPLIN300_MPI-ESM-LR_historical+rcp85_r3i1p1_19500101-21001231.nc'
url_nrcan = 'http://boreas.ouranos.ca:8083/thredds/dodsC/birdhouse/nrcan/nrcan_canada_daily_v2/tasmax/nrcan_canada_daily_tasmax_2016.nc'
url_nrcan_ind = 'http://boreas.ouranos.ca:8083/thredds/dodsC/birdhouse/cccs_portal/indices/Final/ANUSPLIN/txgt_30/YS/nrcan_canada_1950-2017_txgt_30_YS.nc'

ds1 = xr.open_dataset(url_ind,decode_times=False)
ds2 = xr.open_dataset(url_raw,decode_times=False)
ds3 = xr.open_dataset(url_nrcan,decode_times=False)
ds4 = xr.open_dataset(url_nrcan_ind,decode_times=False)

np.testing.assert_array_equal(ds1.lon,ds2.lon)
np.testing.assert_array_equal(ds1.lat,ds2.lat)
print('BCCAQV2 index and raw have identical coordinates')

np.testing.assert_array_equal(ds3.lon,ds4.lon)
np.testing.assert_array_equal(ds3.lat,ds4.lat)
print('ANUSPLIN index and raw have identical coordinates')


np.testing.assert_almost_equal(ds4.lon.values,ds1.lon.values,decimal=5)
np.testing.assert_almost_equal(np.flipud(ds4.lat.values),ds1.lat.values,5)
print('NRCAN index & BCCAQv2 index have identical coordinates to 5 decimal places')

np.testing.assert_almost_equal(ds3.lon.values,ds2.lon.values,decimal=5)
np.testing.assert_almost_equal(np.flipud(ds3.lat.values),ds2.lat.values,5)
print('NRCAN raw & BCCAQv2 raw have identical coordinates to 5 decimal places')

**Comment by ryanclimateatlas** [comment]
@tlogan2000 Ok thanks for providing this code. I now see what has happened. In short, they are good -- no shift in lat/lon bounds from BCCAQv2 data. I was referencing an older version of ANUSPLIN, which had lat_0 = 41.0 and lon_0 = -141.0. These have since been changed, with the new lat_0 = 41.04. So the issue was on my end, my apologies for not noticing that earlier.

**Comment by dvdkamp** [comment]
@tlogan2000, a few questions about the thredds server:

 - I'm assuming you'd like us to look at files in the `*/ensemble_percentiles/*` directories?
 - What is the distinction between `Ys/`, `QS-DEC/` and `MS/`?

**Comment by tomLandry** [comment]
Moving priority up a notch so we tackle this next sprint, knowing the work is getting organized.

**Comment by tlogan2000** [comment]
@dvdkamp - sorry abbreviations are shorthand for resampling frequencies in xclim
YS - year start :  yearly files
MS - month start : monthly files
QS-DEC - quarterly starting in december : Seasonal files 
Note* the seasonal stuff was flagged as not a priority so many directories will not have this option but I didn't delete work that was already completed...

**Comment by dvdkamp** [comment]
@tlogan2000, @ryanclimateatlas, @tomLandry 

Does it make sense for CCCS and PCC to do independent validation on the data? I would think that getting the data right is important enough that it makes sense to have some redundancy... Thoughts?

**Comment by tlogan2000** [comment]
I won't refuse...  double / triple checking etc. would be great if time is available on your ends

**Comment by tomLandry** [comment]
Sounds good indeed. Is there a tradeoff to it? Something else that won't be validated (or advanced) in the meantime by CCCS? Should we scrum on this, or take turns? Is it urgent, or can it wait 2 weeks?

**Comment by dvdkamp** [comment]
Considering the high priority, I think it would be worth it. I don't forsee that this will get in the way of CCCS validating other tasks (I'm delegating some of the grunt work to a student)

**Comment by tomLandry** [comment]
It settled then!

**Comment by ryanclimateatlas** [comment]
Hi all, we just had a meeting to decide on our QA/QC methodology. On the Atlas, we provide the 24 model ensemble mean for each variable. Thus, our first step will be to produce the same 24-model means from the netcdf files up on the THREDDS server. We will then provide to the group i) a set of 30-year average ensemble mean netcdf files and map images from the Atlas; ii) the same set of netcdf files and map images we produce from the 24 individual model files up on THREDDS, and finally; iii) a set of netcdf files and map images that are the differences (deltas) between i and ii. And of course hopefully these deltas come out as zeros. After we do this for as many variables as we think are required for a rigorous analysis, we will move towards computing some of the percentile values as well. @dvdkamp and @tomLandry hopefully this helps explain how we are approaching this -- perhaps you could also provide us with a brief plan of attack from your end. We can then coordinate at some point if needed after the first round of QA checks.

**Comment by tomLandry** [comment]
Thanks for the report @ryanclimateatlas. I suggest we keep the discussion open here on GitHub, but when we reach mutual understanding and a critical mass of information, we should move to Confluence. I opened the page (empty for now) https://ccdpwiki.atlassian.net/wiki/spaces/CCDP/pages/64684036/Data+QA+QC

As for CRIM's side, we'll probably be a bit more active to support Ouranos for QC of the metadata itself (see https://github.com/Ouranosinc/pavics-sdi/issues/37), instead of QA of the data. More generally, we'll be on the lookout of what can be automated with our continuous integration frameworks, and into the development and deployment process (https://github.com/CanadianClimateDataPortal/Canadian-Climate-Data-Portal/projects/1)

**Comment by dvdkamp** [comment]
Hi All,

CCCS is taking a simpler spot-check approach and focusing on the ensemble percentiles of the indices.

 - For all RCPs and percentiles of a given variables we are:
    - inspecting maps of random time steps
    - inspecting 150 year time-series  of random grid points
    - examining the distribution of these variables

We are starting at the top of the Interim Priority list and working our way down. 

one question: @tlogan2000 @habitatseven, what is the deadline for this QA work?

**Comment by tomLandry** [comment]
@dvdkamp without necessarly wanting to commit Travis or Jamie or anyone else on this one on scedule, btu taking the _agile_ metho stance... The issue is currently "In progress", and flagged as high priority. Just seeing discussion here makes me believe its true! Overall, we look for issues to be "done" in less than two sprints time (1 month). We do allow ourselves to open side issues or to iterate, but we need to move from left to right and fast.

So that being said, it would mean that this would be done with good confidence before end of sprint 4. I added a milestone of this (Milestone 2 - March 31st), but we should clear this prior to the launch of course. Mid-March seems reasonable, albeit a bit tight. But we'll but tight on everything anyways.

**Comment by dvdkamp** [comment]
@tomLandry,

Thanks for this! Still getting used to the agile approach!

**Comment by tomLandry** [comment]
No problem, and I suspect you're not alone in that situation. That's why I'm "board master"! Also, note that everything that is in the TODO column is also important and will _probably_ be done in the next sprint, or the one after. It's not too soon to ask around for task in the TODO, but more to poll and get more precise acceptation conditions. As of today, we're pretty light on formal descriptions and acceptation conditions, but that will change as people get a better sense of the process - and actually use GitHub...

We try to keep the notion of milestone in sync with the notion of sprints, so we have a better view of what's ahead and to report in more classical project management terms. Milestones are commited into every participation agreement with partners by the way. But we still need agile on top of this.

**Comment by ryanclimateatlas** [comment]
Quick QA note. Not all of the BCCAQ model files provide full coverage of Canada -- many models are missing the very northern tip (see attached image).
![image](https://user-images.githubusercontent.com/47456538/53358122-114e5500-38f5-11e9-80b0-43c4d9036604.png)
 On the Climate Atlas, we set this region to NaNs; however we've noticed that the ouput data being stored on the THREDDS server, as well as CCCS's climate data website, provide data for this area. Just want to make sure that the computation done here are taking into account the fact that there are fewer models in the ensemble. @tlogan2000, any thoughts?
![image](https://user-images.githubusercontent.com/47456538/53358346-a81b1180-38f5-11e9-97ae-ed847d8bb118.png)

**Comment by tlogan2000** [comment]
thanks for the info:

For the portal, the way the ensemble statistics calculations are written it will return NaN if even one simulation has missing values.  i.e. If the ensemble statistics netcdf file has a value if means that that grid cell is there for all simulations (for a given rcp).   I would assume that this means that all ensemble stat files are missing this northern slice of data?

**Comment by dvdkamp** [comment]
I will reach out the Climate Research Division at ECCC who created the ensemble maps for CCCS' climate data viewer.

**Comment by dvdkamp** [comment]
Note, I believe that this boundary shows up in the BCCAQv2 50th percentile shown on the climate data viewer:

https://climate-viewer.canada.ca/climate-maps.html#/?t=annual&v=tmean&d=dcs&r=rcp85&cp=-78.19123550744055,81.55801337735818&z=6&ts=3
(may take a few seconds to load)

**Comment by ryanclimateatlas** [comment]
@tlogan2000 @tomLandry  you'll be happy to see these maps (see attached ppt file). Hopefully these map speak for themselves; basically the last slide is delta map showing the difference between cooling degree days the way we computed it vs. the way Ouranos computed it... and the difference is zero! yay. (well, technically NOT zero... there are differences +/- 0.001, which can be chalked up to computer architecture and rounding).
[Comparison cooldd.pptx](https://github.com/CanadianClimateDataPortal/Canadian-Climate-Data-Portal/files/2916249/Comparison.cooldd.pptx)

**Comment by ryanclimateatlas** [comment]
we will continue to produce maps and share again here once we have a larger collection. One interesting thing to watch for in our next batch of tests is going to be the +30C maps... here it turns out there is a slight difference in methodology between the PCC and Ouranos.... we call a +30 day a day when tasmax is > or = +30, whereas (on Confluence) the Xclim definition is just >30. @tlogan2000 maybe you can verify that if you don't mind?

**Comment by ryanclimateatlas** [comment]
I'm continuing the QA/QC convo on Confluence, where we have a nice new page for comments. https://ccdpwiki.atlassian.net/wiki/spaces/CCDP/pages/64684036/Data+QA+QC

**Comment by tomLandry** [comment]
Priority was raised to Blocker (pretty much critical) as this work should culminate in the March 31st release.

**Comment by dvdkamp** [comment]
We are working on that now and will have something for you tomorrow

**Comment by tomLandry** [comment]
After discussion with project leader, and considering documentation here and on Confluence, work is considered done and collaborative. Closing this issue. If there are outstanding points, please create a new targetted issue. Similarly, further QA tasks during Beta phase will be tracked separately.

**Comment by tomLandry** [comment]
One follow up issue here: https://github.com/CanadianClimateDataPortal/Canadian-Climate-Data-Portal/issues/71
