### ISSUE TITLE
Identify content for portal

### ISSUE THREAD

**Issue by MarcAndreDubuc** [CanadianClimateDataPortal/Canadian-Climate-Data-Portal#44]
As described here: https://ccdpwiki.atlassian.net/wiki/spaces/CCDP/pages/edit/51642369?draftId=51642378&draftShareId=3c4a310c-79c3-4c86-b445-e3fe3f0b64ac&

**Comment by MarcAndreDubuc** [comment]
As discussed, see link https://github.com/CanadianClimateDataPortal/Canadian-Climate-Data-Portal/issues/20

**Comment by tomLandry** [comment]
So TO DO here is another round in Confluence to integrate between Type of contents (https://ccdpwiki.atlassian.net/wiki/spaces/CCDP/pages/51642369/Content) to portal elements (https://ccdpwiki.atlassian.net/wiki/spaces/CCDP/pages/57671685/Content+required+by+page). @MarcAndreDubuc I think I've heard you were on this, right? That would then constitute sufficient work to go to validate. @isacharron and/or Diane Chaumont could do the validation.

**Comment by dvdkamp** [comment]
@MarcAndreDubuc,  @isacharron, 

I can validate this table:
https://ccdpwiki.atlassian.net/wiki/spaces/CCDP/pages/57671685/Content+required+by+page

If no one's done it yet.

**Comment by tomLandry** [comment]
I say go ahead Derek. I suggest you validate a bit more on the "work process" side than exactness/completeness of the tables. Also, consider that Priority 1, the glossary, was delivered here https://github.com/CanadianClimateDataPortal/Canadian-Climate-Data-Portal/issues/50

**Comment by dvdkamp** [comment]
@tomLandry I'm not 100% sure what you mean by the "work process" side... I just want to be sure before I launch into the task.

**Comment by tomLandry** [comment]
Sure. Basically, I'd like your opinion on the table themselves, if they support the identification of content and can be expanded to its validation. Does it seems like a good structure going forward. As per opposition of the actual content of the tables, the priorities set and so on. On this, we can iterate in the next sprint.

**Comment by dvdkamp** [comment]
A few comments on this [table](https://ccdpwiki.atlassian.net/wiki/spaces/CCDP/pages/57671685/Content+required+by+page) (I'm only commenting on the format of the table itself, as opposed to the actual content of the tables):
 -  Perhaps we could increase the granularity:
    - I.e., on the 'Variable Menu' page, there would individual rows for 
       - Title of menu, 
       - categories of "variables of interest", 
       - names of variables
 - There may be some redundancy here. For instance, content around the training videos appears in both the 'Viewer Selection" page and the "Training Page"
 - Also, it is important to include pages that do not yet have designs. However, We may need to wait for those pages to be deigned. Additional pages not yet on the list:
     - Calculate-on-the-fly page
     - "Contact us page"
     - "About" page
     - "Feedback" page
     - Others?

**Comment by tomLandry** [comment]
Thanks @dvdkamp. I will update the tables accordingly, as we seek continuous process improvement. For content of that table (Content required by page), one important question is if/how it's useful from @habitatseven perspective. If we see that table only from the validation standpoint, and it's not used by/with H7, something's missing.

I think the table found on https://ccdpwiki.atlassian.net/wiki/spaces/CCDP/pages/51642369/Content might be more useful short-term, for the agile metho. Basically, this should depict what will be coming next in the content production (priority column). Maybe an column for assignation of production would be in order. We can stay flexible for validation for now, not committing people too much ahead of time.

**Comment by tomLandry** [comment]
Content has been mostly all identified from the Portal designs and into a GoogleDocs where we will track production both in French and English. Missing pages are tracked. This issue of "identification" has been solved, but production and validation are still outstanding. More precise and targetted issues will be opened.
