### ISSUE TITLE
Produce climate indices complete descriptions for prioritized indices

### ISSUE THREAD

**Issue by tomLandry** [CanadianClimateDataPortal/Canadian-Climate-Data-Portal#45]
First, provide a template/example of climate indices description (short description, long description, why it matters, how computed, etc.)

For each prioritized indice, provide descriptions.

Make sure someone abilited to do the "verify" has been identified. More to come on this.

**Comment by huard** [comment]
I can put together a jinja template for an HTML table and feed it the current metadata of our indices as a starting point.

**Comment by tomLandry** [comment]
Hello David. Thanks a lot for checking in. This particular issue is a bit more about getting the process right, from technical writing to "publication" to verification by peers, so it can be used in the portal. Get the Kanban board moving a bit. No worries if not all indices are documented, but I'd like to get an idea of what a single indice documentation will look like.

I can't tell right now how the portal will fetch (or not) those descriptions, so by default I assume that someone will manually copy content into a CMS. So don't spend too much time beautifying the content. I can imagine a scenario where I go on GitHub to copy the completed description elsewhere - out of your loop. It might break though, because of markup and images. Anyway, you get my point. Raw text is fine for a starting point, awaiting for portal ingestion.

**Comment by tlogan2000** [comment]
David if you can have a first go at this that would be great.

**Comment by huard** [comment]
https://github.com/Ouranosinc/xclim/pull/145

**Comment by tomLandry** [comment]
Moving priority to high so it's tackled next sprint.

**Comment by huard** [comment]
cold_spell_days and cold_spell_duration_index use two different definitions of cold spells. I think we should use different expressions for different definitions. Candidates: absolute_cold_spell, relative_cold_spell, cold_snap, cold_wave.

**Comment by tlogan2000** [comment]
Ok for the cold spell distinctions ... agree it is quite confusing 
for long_name I find as lower case on the cf-conventions description:
http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/build/ch03s02.html

Cannot much in terms of whether math expression can be present though..

**Comment by tlogan2000** [comment]
I think I like absolute an relative cold_spells ... will make people think about what a relative cold_spell is exactly

**Comment by tomLandry** [comment]
We consider that definitions found in https://ccdpwiki.atlassian.net/wiki/spaces/CCDP/pages/66191683/Indices+descriptions forms a complete list. We need to add mathematical definitions as a next priority.
