### ISSUE TITLE
Re-prioritize indices and variables based on technical constraints

### ISSUE THREAD

**Issue by tomLandry** [CanadianClimateDataPortal/Canadian-Climate-Data-Portal#48]
As discussed here, a second pass is needed. https://github.com/CanadianClimateDataPortal/Canadian-Climate-Data-Portal/issues/11

**Comment by tomLandry** [comment]
Other consideration: https://github.com/CanadianClimateDataPortal/Canadian-Climate-Data-Portal/projects/1

**Comment by tomLandry** [comment]
As discussed, the new table is found here: https://ccdpwiki.atlassian.net/wiki/spaces/CCDP/pages/57638919/Interim+Prioritization
We had the idea to add additional columns to manage the production-download-ingestion process, as well to links to the general content - including "Why it matters". Color codes will be added.

**Comment by dvdkamp** [comment]
I only have a few comments and questions on the prioritization:

Some of these suggestions may go against what I originally proposed, but I reserve the right to change my mind :)

**comments** 

- #9a:  Heat waves max length:
  - What is the rank of this index? 
  - Will this be calculated for each year? If so, my guess is that it would be quite noisy... 
  - I would give this a low priority as I think it would be more important that people simply know that heat wave frequency will increase, n

- 21: txgt_25: days with tmax > 25 (summer days)
  - For the sake of northerners, I would increase the priority of this index. In fact, I would put it right below txgt_30 in the list. 

- Also for the sake of northerners, I would suggest a "days with tmax > 20" index as well. This would be really useful for more northern areas. I don't know if that is a big ask, though\

- max of daily tmax, min  of daily tmin
  - the more I think about these indices, the more I think that they would be really interesting in "painting a picture" of the future climate,
   - I would increase the priority of these to above the more technical indices (so say above TG90p)


**questions**

 - tn_mean, tx_mean, prcptot, tg_mean
   - What are the priority of these? I would think these are redundant if we are already providing yearly means and totals of the raw temperature and precipitation variables...
 - What is the priority of "Cold days TNm25,"

**Comment by tomLandry** [comment]
Derek don't get me wrong, your questions and comments here are **very** useful. This issue was opened more on basis of _technical_ issues (data size, complexity of computation, reliability of algorithm, etc.). I guess that I could have added a lot more descriptions to it! 

The idea was a bit more to have a cutoff line on the _number_ of indices first, before going back to prioritization on other merits. I was also looking for @tlogan2000 and @habitatseven to document their thoughts - as discussed in Montreal's meeting a couple of week ago. 

That being said, thanks for the input! I invite the other experts to pitch in.

**Comment by tomLandry** [comment]
I'm tempted to lower the priority of this, on basis that a majority of indices are already computed and hosted, and that performance tests from @habitatseven on unchunked data indicates a MAJOR decline in potential volume size (compared to PostGres approach). Less risky now. @MarcAndreDubuc thoughts?

**Comment by dvdkamp** [comment]
@tomLandry, sorry for the noise!

**Comment by tomLandry** [comment]
Never be sorry to contribute! This is signal!

**Comment by tomLandry** [comment]
We consider that as we have most of the indices computed, and that technical constraints (a.k.a. technical risk) linked to them are now slim. The prioritization of indices now has more to do with content (mathematical description, key concepts) and use in the sector module (where it support case studies).
