### ISSUE TITLE
Produce comparative performance test between PostGres and NetCDF unchhunked

### ISSUE THREAD

**Issue by tomLandry** [CanadianClimateDataPortal/Canadian-Climate-Data-Portal#49]
As stated here https://github.com/CanadianClimateDataPortal/Canadian-Climate-Data-Portal/issues/48, we need to define a maximal number of indices likely based on overall data requirements. From that discussion, we also proposed a test on NetCDF unchunked data https://pavics.ouranos.ca/thredds/catalog/birdhouse/testdata/Chunking_Netcdf/catalog.htm.

There is a need to compare a large number of random access to both PostGres and the NetCDF in order to compare and contrast performance gains VS increased disk space requirements. Also, a better profiliing of performance between these two access methods can help determine hybrid scenarios.

**Comment by dbyrns** [comment]
To quote Jamie, the best format allowing small disk footprint and good performance is : '150 year, all RCP ensembles, uncompressed, unchunked'

**Comment by tomLandry** [comment]
So then that would kinda settle it for the performance aspect - the topic of this issue. We've had several exchange, I'd like to see that in Confluence soon. But we can move this to validate, and it would not stay there for long. There is still a need to evaluate the data size required for indices though, but there's another issue for that https://github.com/CanadianClimateDataPortal/Canadian-Climate-Data-Portal/issues/48.

**Comment by tomLandry** [comment]
We have our answer. Additionally, we need to consider if we place this 'visualisation' data on SSD.
