### ISSUE TITLE
IDF curves integration to the portal

### ISSUE THREAD

**Issue by MarcAndreDubuc** [CanadianClimateDataPortal/Canadian-Climate-Data-Portal#54]

**Comment by dvdkamp** [comment]
I'm wondering about the status of this issue. Has the connection been made to the original ECCC data owners? Have we figured out how the data will be transfered to the portal? If these questions have yet to be answered perhaps I can look into it?

**Comment by tomLandry** [comment]
As this should be settled for Portal V1, hence milestone 2, this is marked blocker.

**Comment by tlogan2000** [comment]
For info : The long-anticipated update appears to be online here:
ftp://ftp.tor.ec.gc.ca/Pub/Engineering_Climate_Dataset/IDF/IDF_Files_Fichiers/

**Comment by dvdkamp** [comment]
The FTP site that @tlogan2000 provided above is super unstable. they also have a copy of the dataset on google drive:

https://drive.google.com/drive/folders/1VzJdW7DUIA3mpqz8mA8jqG6LdCqy_UOF

**Comment by dvdkamp** [comment]
It looks like @habitatseven will store their own copy of the dataset that the portal will pull from. @habitatseven, does that extra work mean that the IDF curves will slip below the station data in terms of priority?

**Comment by dvdkamp** [comment]
I like the looks of the IDF page! But Before I validate it and move it to "Done" I wanted to check: @habitatseven , is there a way to allow users to search for station names in the search bar at the top left of the map? In that case, it would be good for the initial text in the search bar to say "Search for City/Town/Station Name" or something like that

**Comment by tomLandry** [comment]
Sorry to steal your thunder Derek, I'm moving stuff on the board. I've seen both the demo app and integration into portal so I validate it. It's "integrated". I moved your question about searching as a new item.
