### ISSUE TITLE
Prepare various sample requests for PAVICS/Finch

### ISSUE THREAD

**Issue by tomLandry** [CanadianClimateDataPortal/Canadian-Climate-Data-Portal#58]
This issue is a follow-up on https://github.com/CanadianClimateDataPortal/Canadian-Climate-Data-Portal/issues/7. The outcomes can be documented here https://ccdpwiki.atlassian.net/wiki/spaces/CCDP/pages/11698239/Indices+computation

What is needed is more samples requests for **daily** BBCAQv2 data (https://pavics.ouranos.ca/thredds/catalog/birdhouse/pcic/BCCAQv2/catalog.html) into both heat_waves processes of Finch. This data is still as far as I know _per model_, and in general we want to discourage downloads or process from single models. We need to find a good way to work around this.

This work does includes subsetting of the daily data through OPeNDAP for small, medium and large bounding boxes. Basically, we do not want to allow a user to process for the whole Canada. Therefore, the input data URL will have to be modified to include the box coordinates.

We need to keep track of processing time for each request. Ideally, we would still have a few requests that would complete in 15 minutes or less, so we can demonstrate the reception of an email confirmation in a single sitting. We can control this execution time by choosing a bounding box size.

Once a certain number of sample requests are ready, we will pass them on to @habitatseven so they can start integration of the API and building a demo page. This work, related to the portal itself, will be conducted in another issue.

**Comment by dbyrns** [comment]
See: https://ccdpwiki.atlassian.net/wiki/spaces/CCDP/pages/68976784/Finch
