### ISSUE TITLE
Geomet station data - Bulk download

### ISSUE THREAD

**Issue by MarcAndreDubuc** [CanadianClimateDataPortal/Canadian-Climate-Data-Portal#74]
- [ ] Possibility to download multiple or all data on a single station
- [ ]  Possibility to download multiple station at the same time by selecting them

Possibility to go through the download section of the portal instead of the vizual mapping representation

**Comment by jordanharding** [comment]
@MarcAndreDubuc by station data, are your referring to the static files (pdf, txt, png) only or is there something else to be included?

![image](https://user-images.githubusercontent.com/13383273/55569057-d945e900-56ce-11e9-8ed5-c1bd188fe1e0.png)

**Comment by dvdkamp** [comment]
@jordanharding, Tha

**Comment by dvdkamp** [comment]
@jordanharding, That's great!
